name: Z_Punishments
version: '${project.version}'
main: me.zeroseven.trial.Punishments
api-version: '1.20'
authors: [ZeroSevenn]
softdepend: [LiteBans]
commands:
  ban:
  mute:
  unban:
  unmute:
  kick:
  history:
  checkban:
  checkmute: